src/atlas.nim
49ba8b89bcb81124597290c2264f13f86449711b regressed to overwrite deps in `atlas.workspace`
=> Add check for deps dir

src/atlas.nim, src/context.nim, src/gitops.nim, src/lockfiles.nim
This PR adds the ability to convert nimble lock files to atlas lock files. It's pretty nice!
It also does: 
- adds `replay` in addition to `rep` for clarity
- prints status updates for deps after running `replay` to help users know what it did
- when `nimble.lock` is passed to `replay` it will use it
- package paths in messages are relative to workspace when using color mode
=> Import nimble locks

atlas.nimble, config.nims, src/atlas.nim, src/confighandler.nim, src/context.nim, src/gitops.nim, src/lockfiles.nim, src/nameresolver.nim, src/nimenv.nim, src/osutils.nim, src/parse_requires.nim, src/runners.nim, src/traversal.nim, tests/tester.nim, tests/unittests.nim, tests/ws_integration/expected/nim.cfg
This depends on https://github.com/nim-lang/atlas/pull/49. 
I needed the ability to export Nimble lockfiles. This makes it possible to maintain a Nimble lockfile with Atlas.
=> Export Nimble lock file

src/atlas.nim, src/context.nim, src/lockfiles.nim, src/nameresolver.nim
- fix `atlas install` where the nimble path wasn't being used correctly
- `atlas replay` will now call `atlas install` to setup nim.cfg if empty or `--cfghere` passed
- `atlas convert` imports the Nim version if found in the nimble.lock
- add `atlas changed` command to print out deps that have changed
- `atlas convert` to use paths relative to current project
=> Tweaks to convert, install, and replay

src/confighandler.nim, src/context.nim, src/lockfiles.nim, src/nameresolver.nim
- `getUrl` normalizes all url's ending in `.git` to prevent false duplicates
- `nimbleConverLock` uses now resolves packages and uses repo name for path
-  improvement to urlOverride logic to properly set updated url's
=> Various fixes

config.nims, src/atlas.nim, src/configutils.nim, src/context.nim, src/gitops.nim, src/lockfiles.nim, src/nameresolver.nim, src/nimenv.nim, src/traversal.nim, tests/tester.nim
Changes:
- Add shallow cloning and fetching by default which speeds up cloning quite a bit (submodules are also shallow)
- Add `--full` option which will do a full clone and call `--unshallow` when needed on existing shallow clones
- Add "version" to lockfiles so `changed` can display versions diffs
- Change lockfiles to use `$deps/deps_path` or `$workspace/pkg` for dirs so that `atlas replay` works in scenarios where users have `depsDir` defined, otherwise lockfiles do weird things
- Change lockfile `nimCfg` and `nimble.contents` to use array of lines for better git diff's and ease of manual modifications / reviews (the previous format is automatically converted)
- `atlas replay --cfgHere` should actually work and not trample the commits by using the packages in the lockfile to create …
=> Lockfile and other improvements

src/atlas.nim, src/lockfiles.nim, src/nameresolver.nim, src/packagesjson.nim, tests/unittests.nim
This allows moving all the dependencies to a location outside of the workspace, so that it contains only user files and atlas configuration.
FR/TODO: make the `packages` directory configurable
=> Move `packages` to `depsDir` from workspace root

src/atlas.nim
While falling back to traversing subdirectories, `detectWorkspace` now returns immediately when a workspace is found.
Why does atlas look there anyway? It was a bit confusing when I tried to `atlas use` outside my workspace and it worked.
Outputting `(.)` in info for a workspace path doesn't help.
=> `detectWorkspace` now returns the first ws-subdir

src/atlas.nim
This PR adds `atlas new <project_name>` command: a bare-bones project initialization.
- A project name is validated with a laxed rule of allowing dashes
- A new directory is created
- A new `.nim` file is created inside, with the project's name as a doc comment.
- Due to how the CLI parser works, a project name can't have `-` as the first character. No loss.
=> Add a command to init a new project

src/atlas.nim, src/gitops.nim
- CLI syntax unified per a mix of man/GNU/IBM command syntax guides.
- `include testdata` moved to gitops immediately prior to the `exec` - the only place that uses the consts.
I'm a bit confused as to how the `TestData` const is used. It lives only inside the `when MockupRun` which is, in turn, set by `atlasTests` define, which I don't see being set anywhere. Shouldn't `nim test` task set this define?
=> CLI syntax unified; `testdata` include moved

src/configutils.nim, src/lockfiles.nim
Properly generate paths for lockfile when passing `--cfgHere`.
=> fix cfgHere re-generation for lockfiles

.github/workflows/ci.yml, atlas.nimble, src/atlas.nim, src/context.nim, src/lockfiles.nim, src/pkgversion.nim
Fixes installing Atlas using Nimble.
Testing by manually running `nimble install https://github.com/elcritch/atlas@\#fix-nimble-install`.
Note if you tried to install the previous version it can Corrupt the Nimble pkgs. In that case you need to do a `rm -Rf ~/.nimble/pkgs/atlas* ~/.nimble/pkgs2/atals*` to remove the old ones.
Also includes fixes for:
- adds test for installing with Nimble
- getting correct URL for repos with alternate URLs (e.g. `windy.elcritch.github.com`)
- fix `[Info] (/Users/jaremycreechley/projs/nims/figuro/vendor) is the current workspace` to log with absolute path
- add `--ignoreUrls` to ignore mismatch URLs when using `replay`
=> fix nimble install and lock replays

.github/workflows/binaries.yml, config.nims
Adds a `buildRelease` task to config.nims for handling the cross xc builds. I tested both macos, linux, and windows builds to ensure they build the correct arch. I did not run them on all the platforms. 
I updated binaries.yml in the CI, but it is untested. Very likely to have things to fix, but the general structure should now be correct.
=> build universal macos and linux arm / arm64 binaries

src/depgraphs.nim
=> fixes #110; make it compatible with Nim 2.0.0

src/atlas.nim, src/confighandler.nim, src/context.nim, src/depgraphs.nim, tests/unittests.nim
=> Honor deps dir for 'atlas init --deps=deps'

src/atlas.nim
When first trying out atlas on an existing project, I was confused why this didn't work:
```
atlas install myfile.nimble
```
Apparently it was expecting:
```
atlas install ./myfile.nimble
```
But the error didn't make that obvious. This change lets you specify the file without `./`
=> Make 'atlas install myfile.nimble' work

.github/workflows/ci.yml
This adds a job to the CI github action to run @beef331's `graffiti` on the master branch.
I'm not sure if this is a good idea, but it would be convenient.
- automatically adds tags for version bumps (e.g. less back and forth)
- make new versions installable by tags
- potential to merge a PR with a bad version bump, but accidental tags can be deleted
- pins to a specific graffiti git hash for sanity reasons
=> Run graffiti when atlas.nimble changes

.gitignore, src/basic/nimblecontext.nim, src/basic/parse_requires.nim, tests/test_parse_requires_when_else.nim
Fixes parsing issue with Figuro nimble files due to erroneous ambigous Nimble files. This updates the nimble file checking to prefer the packages "short name" if there's ambiguity.
=> Fix figuro nimble parsing issue

atlas.nimble, src/atlas.nim, src/basic/gitops.nim, tests/tgitops.nim
Previously update would only look for new tags. This breaks on repos not using tags for versioning. This PR improves it to first looks for tags, if none are found it will update the repo directly.
The repo update command has also been changed to `git fetch origin "refs/heads/*:refs/heads/*" "refs/tags/*:refs/tags/*"` which will update origin as well as try to update any local branches. This should improve workflows. I left an option to only update the origin refs in case it causes trouble or it's wanted. Currently it's not plumbed out. 
Finally, fixed the documentation. There's only `atlas update`.
=> improve `update` command

atlas.nimble, src/basic/versions.nim, src/depgraphs.nim, tests/test_headtip.nim
Fixes https://forum.nim-lang.org/t/13435
Note that httpbeast doesn't tag the last release 0.4.2. You need to include:
```
requires "httpbeast#head"
```
=> Fix #head version not included bug
